{ selfPath, ... }: {
  imports = [
    (selfPath "home/common/atuin.nix")
    (selfPath "home/common/bat")
    (selfPath "home/common/bloom")
    (selfPath "home/common/busy-nas")
    (selfPath "home/common/btop")
    (selfPath "home/common/catppuccin.nix")
    (selfPath "home/common/cerberus")
    (selfPath "home/common/claude")
    (selfPath "home/common/codex")
    (selfPath "home/common/cupcake")
    (selfPath "home/common/direnv")
    (selfPath "home/common/eza")
    (selfPath "home/common/fastfetch")
    (selfPath "home/common/ghostty")
    (selfPath "home/common/git")
    (selfPath "home/common/go-task")
    (selfPath "home/common/hermes")
    (selfPath "home/common/k9s")
    (selfPath "home/common/lazydocker")
    (selfPath "home/common/lazygit")
    (selfPath "home/common/nh.nix")
    (selfPath "home/common/nix-index.nix")
    (selfPath "home/common/nvim")
    (selfPath "home/common/opencode")
    (selfPath "home/common/packages.nix")
    (selfPath "home/common/pharos")
    (selfPath "home/common/ssh-agent.nix")
    (selfPath "home/common/tmux")
    (selfPath "home/common/vesktop.nix")
    (selfPath "home/common/yt-dlp")
    (selfPath "home/common/zen")
    (selfPath "home/common/zoxide")
    (selfPath "home/common/zsh")
  ];
}
